name: Deploy NGINX to App Runner

on:
  push:
    branches:
      - main

  workflow_dispatch:

permissions:
  id-token: write
  contents: read

env:
  AWS_REGION: us-east-1
  ECR_REPOSITORY: my-nginx
  IMAGE_TAG: latest

jobs:

 
  infrastructure:
    name: Create Infrastructure
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v6
        with:
          role-to-assume: ${{ secrets.AWS_GITHUB_ROLE_ARN }}
          role-session-name: GitHubActions
          aws-region: ${{ env.AWS_REGION }}
          audience: sts.amazonaws.com

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        working-directory: terraform
        run: terraform init

      - name: Terraform Validate
        working-directory: terraform
        run: terraform validate

      - name: Create Infrastructure
        working-directory: terraform
        run: terraform apply -auto-approve -var="deploy_app_runner=false"


 
  push-nginx:
    name: Push NGINX to ECR
    runs-on: ubuntu-latest

    needs: infrastructure

    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v6
        with:
          role-to-assume: ${{ secrets.AWS_GITHUB_ROLE_ARN }}
          role-session-name: GitHubActions
          aws-region: ${{ env.AWS_REGION }}
          audience: sts.amazonaws.com

      - name: Login to ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Pull NGINX
        run: docker pull nginx:latest

      - name: Tag NGINX
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        run: docker tag nginx:latest $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG

      - name: Push NGINX
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        run: docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG


  
  deploy:
    name: Deploy App Runner
    runs-on: ubuntu-latest

    needs: push-nginx

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v6
        with:
          role-to-assume: ${{ secrets.AWS_GITHUB_ROLE_ARN }}
          role-session-name: GitHubActions
          aws-region: ${{ env.AWS_REGION }}
          audience: sts.amazonaws.com

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        working-directory: terraform
        run: terraform init

      - name: Deploy App Runner
        working-directory: terraform
        run: terraform apply -auto-approve -var="deploy_app_runner=true" -var="image_tag=$IMAGE_TAG"


      - name: Get App Runner URL
        working-directory: terraform
        run: |
          echo "======================================"
          echo "NGINX App Runner URL:"
          terraform output -raw apprunner_service_url
          echo "======================================"
